#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_SKYBOX, RENDER_PRIORITY, RENDER_TEST ,RENDER_BLOCK ,RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum CHANNELID
	{
		SOUND_BGM,
		SOUND_EFFECT,
		SOUND_BUTTON,
		SOUND_UI,
		SOUND_WORLD,
		MAXCHANNEL
	};

	enum TILEID { TILE_NORMAL, TILE_EMPTY, TILE_OBSTACLE, TILE_END };

	enum DIRECTION { DIR_FORWARD, DIR_LEFT, DIR_RIGHT, DIR_BACKWARD, DIR_END };

	enum DEATHTYPE
	{
		DEATH_NONE,
		DEATH_COLLISION,
		DEATH_FALL,

		DEATH_END
	};

	enum JSGAMESTAGE { JSSTAGE_INTRO, JSSTAGE_COUNTDOWN, JSSTAGE_PLAY, JSSTAGE_END };
}
#endif // Engine_Enum_h__
